spring:
  data:
    mongodb:
#      host: 192.168.219.129
      host: 192.168.2.104
      database: tcRepo
      port: 27017
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
server:
  context-path: /ee
  port: 8081